cooldown_timer: 25
minimum_hug_distance: 30
easter_eggs:
    creeper:
      - "Trying to hug a creeper is a terrible idea"
    spider:
      - "Nope. Nope! Nope!!"
      - "Little known fact: Spiders are the best huggers in the world. They have 8 arms!"
    zombie:
      - "Do you want more zombies? Because that's how you get more zombies!"
    skeleton:
      - "That would be like hugging a broom"
    slime:
      - "Ewww..."
    magmacube:
      - "Sure, hugging a squishy ball of lava sounds like fun..."
    wither:
      - "You've been withered! Just kidding!"
    witch:
      - "Minecraft? I thought you said Witchcraft!"
      - That was magical...why don't you stop by and stay for a spell.
    enderman:
      - "Just don't look"
    husk:
      - "The hug is nice but now you feel hungry for some reason"
    shulker:
      - "A hug that is lighter than air"
    illager:
      - "Johnny?"
    blaze:
      - "Hot! Hot! Hot!"
      - "That hug was lit!"
    ghast:
      - "There there... don't cry"
      - "I'm all aghast!"
    dinnerbone:
      - "Free Hugs!"
    autcraft:
      - "Hugging a computer server isn't as pleasant as you'd expect"
    broadcast:
      - "Broadcast prefers bacon"
    group:
      - "Group Hug!"
    console:
      - "Console has no arms"
    bessie:
      - "The lag feels like it slips away..."
    bc:
      - "Please, call me Broadcast"
    villager:
      - "Villagers only trade emeralds"
      - "I would hug you but my sleeves are stuck together"
    polarbear:
      - "My turn... BEAR HUG!"
    bacon:
      - "Why are you hugging? EAT."
    sheep:
      - "So flooooofy!!!"
    pig:
      - "You hug your uncooked bacon"
    cow:
      - "You really mooooved me with your hug."
    cactus:
      - "Hugging a cactus is never a good idea"