cooldown_timer: 25
minimum_hug_distance: 30
easter_eggs:
    creeper: "Trying to hug a creeper is a terrible idea"
    spider: "Nope. Nope! Nope!!"
    zombie: "Do you want more zombies? Because that's how you get more zombies!"
    skeleton: "That would be like hugging a broom"
    slime: "Ewww..."
    wither: "You've been withered! Just kidding!"
    dinnerbone: "Free Hugs!"
    autcraft: "Hugging a computer server isn't as pleasant as you'd expect"
    broadcast: "Broadcast prefers bacon"
    group: "Group Hug!"
    console: "Console has no arms"
    bessie: "The lag feels like it slips away..."
    enderman: "Just don't look"
    magmacube: "Sure, hugging a squishy ball of lava sounds like fun..."
    bc: "Please, call me Broadcast"
    husk: "The hug is nice but now you feel hungry for some reason"
    shulker: "A hug that is lighter than air"
    villager: "Villagers only trade emeralds"
    illager: "Johnny?"
    blaze: "Hot! Hot! Hot!"
    ghast: "There there... don't cry"
    cactus: "Hugging a cactus is never a good idea"
    polarbear: "My turn... BEAR HUG!"
    bacon: "Why are you hugging? EAT."
    sheep: "So flooooofy!!!"
    pig: "You hug your uncooked bacon"
    cow: "You really mooooved me with your hug."
    witch: "Minecraft? I thought you said Witchcraft!"